<?php
function shiftkey_h2_typography_options( $args = array() ){
    $options  = array(
        array(
            'id'       => 'h2-xs',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H2 extra small', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the global h2 font properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',  
                'letter-spacing' => '',              
                'line-height' => '',             
            ),
        ),
        array(
            'id'       => 'h2-sm',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H2 small', 'shiftkey' ),
            'subtitle'    => esc_attr__( 'h2.h2-sm', 'shiftkey' ),
            'desc' => esc_attr__( 'Specify the h2 small properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',
                'letter-spacing' => '',              
                'line-height' => '',               
            ),
        ),
        array(
            'id'       => 'h2-md',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H2 medium', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h2 medium properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',  
                'letter-spacing' => '',              
                'line-height' => '',             
            ),
        ),
        array(
            'id'       => 'h2-lg',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H2 large', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h2 large properties.', 'shiftkey' ),           
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '', 
                'letter-spacing' => '',              
                'line-height' => '',              
            ),
        ),
        array(
            'id'       => 'h2-xl',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H2 extra large', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h2 extra large properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',
                'letter-spacing' => '',              
                'line-height' => '',               
            ),
        ), 
        array(
            'id'       => 'h2-huge',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H2 huge', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h2 huge properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',  
                'letter-spacing' => '',              
                'line-height' => '',              
            ),
        ),
    );
    return $options;
}