<?php
function shiftkey_h5_typography_options( $args = array() ){
    $options  = array(
        array(
            'id'       => 'h5-xs',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H5 extra small', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the global h5 font properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h5.h5-xs'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h5-sm',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H5 small', 'shiftkey' ),
            'subtitle'    => esc_attr__( 'h5.h5-sm', 'shiftkey' ),
            'desc' => esc_attr__( 'Specify the h5 small properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h5.h5-sm'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h5-md',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H5 medium', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h5 medium properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h5.h5-md'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h5-lg',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H5 large', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h5 large properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h5.h5-lg'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h5-xl',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H5 extra large', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h5 extra large properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h5.h5-xl'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ), 
        array(
            'id'       => 'h5-huge',
            'type'     => 'typography',
            'title'    => esc_attr__( 'H5 huge', 'shiftkey' ),
            'subtitle' => esc_attr__( 'Specify the h5 huge properties.', 'shiftkey' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h5.h5-huge'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
    );
    return $options;
}