<?php
add_action( 'vc_load_default_templates_action','shiftkey_content_sections_for_vc' ); // Hook in
function shiftkey_content_sections_for_vc() {
	$templates = array();
	$empty_title = $empty_subtitle = '';
	$empty_title = ''.esc_html($empty_title).'';
	$empty_subtitle = ''.esc_html($empty_subtitle).'';

	$templates['Section: Content 01'] = '[vc_section section_type="content" content_type="1" bg_class="bg-tra" parallax_image_attachment="inherit" el_class="content-section division"][vc_row][vc_column width="1/2" el_class="txt-block pc-30"][perch_hero_text name="Beauty of simplicity" name_font_container="tag:span|text_color:blueyonder-color|text_underline:none|text_transform:uppercase|font_weight:500|" '.esc_html($empty_title).' title_font_container="tag:h3|size:md|text_color:dark-color|text_underline:none|" '.esc_html($empty_subtitle).' subtitle_font_container="tag:p|size:md|text_color:lightgrey-color|text_underline:none|" el_class="" mbottom="mb-30" pleft="pl-30" pright="pr-30"][perch_hero_text name_font_container="tag:span|text_color:purple-color|text_underline:none|" title="Enhance your website design with ShiftKey" title_font_container="tag:h3|size:md|text_color:dark-color|text_underline:none|" '.esc_html($empty_subtitle).' subtitle_font_container="tag:p|size:md|text_color:default-color|text_underline:none|" enable_content_list="yes" list_type="cbox-1" content_list="Velna iaculis odio auctor integer congue impedit magna viverra at dolor vitae donec mauris lectus laoreet gestas neque undo luctus feugiat. Justo integer at odio velna vitae auctor integer congue,An enim nullam tempor sapien gravida donec pretium and ipsum porta justo integer at velna vitae auctor integer congue a magna ipsum purus pretium ligula rutrum luctus ultrice. Aliquam a augue suscipit luctus neque purus ipsum neque dolor feugiat" el_class="" pleft="pl-30" pright="pr-30"][/vc_column][vc_column width="1/2"][perch_image align="text-center" custom_src="'.get_template_directory_uri().'/images/image-02.png" el_class="img-block"][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Content 02'] = '[vc_section section_type="content" content_type="2" parallax_image_attachment="inherit" css=".vc_custom_1557389460312{background-image: url(http://localhost/projects/shiftkey/wp-content/uploads/2019/05/blue-textured.jpg?id=1288) !important;}"][vc_row][vc_column width="1/2"][perch_hero_image display_as="0" custom_src="'.get_template_directory_uri().'/images/image-01.png" el_class="img-block"][/vc_column][vc_column width="1/2" el_class="txt-block"][perch_content_text name="Handling With Ease" name_font_container="tag:span|text_color:white-color|text_underline:none|extra_class:section-id|" title="Enhance your website design with ShiftKey" title_font_container="tag:h3|size:md|text_color:white-color|text_underline:none|" subtitle="An enim nullam tempor sapien gravida donec pretium ipsum porta justo integer at odio velna vitae auctor integer congue magna purus pretium ligula rutrum luctus ultrice aliquam a augue suscipit" subtitle_font_container="tag:p|text_color:white-color|text_underline:none|" enable_content="" el_class="section-id" pleft="pl-30" pright="pr-30"][/perch_content_text][perch_content_text name="" name_font_container="tag:span|text_color:white-color|text_underline:none|extra_class:section-id|" '.esc_html($empty_title).' title_font_container="tag:h3|size:md|text_color:default-color|text_underline:none|" subtitle="Features Never Stop" subtitle_font_container="tag:h5|size:md|text_color:default-color|text_underline:none|" enable_content="" enable_content_list="yes" content_list="Fringilla risus nec luctus mauris orci auctor purus euismod pretium purus pretiumligula rutrum tempor sapien,Quaerat sodales sapien undo euismod purus blandit,Nemo ipsam egestas volute turpis dolores ut aliquam quaerat sodales sapien undo pretium purus" el_class="section-id white-color" mbottom="mb-40" pleft="pl-30" pright="pr-30"][/perch_content_text][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 03'] = '[vc_section section_type="content" content_type="3" bg_class="bg-tra" parallax_image_attachment="inherit" el_class="content-section division"][vc_row][vc_column][perch_list_tab list_group="%5B%7B%22title%22%3A%22Feature%20Integration%22%2C%22subtitle%22%3A%22Semper%20lacus%20cursus%20porta%2C%20feugiat%20primis%20in%20luctus%20ultrice%20tellus%20potenti%20neque%20dolor%20in%20primis%20congue%22%2C%22source%22%3A%22external_link%22%2C%22custom_src%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fimage-02.png%22%2C%22img_size%22%3A%22thumbnail%22%2C%22external_img_alt%22%3A%22External%20image%22%2C%22video_link%22%3A%22https%3A%2F%2Fwww.youtube.com%2Fembed%2FSZEflIVnhH8%22%2C%22icon_class%22%3A%22tra%22%2C%22img_link_target%22%3A%22_self%22%7D%2C%7B%22title%22%3A%22Comments%20and%20Mentions%22%2C%22subtitle%22%3A%22Lacus%20cursus%20porta%2Cfeugiat%20primis%20congue%20magna%20purus%20at%20pretium%20ligula%20rutrum%20luctus%20and%20ultrice%20tellus%22%2C%22source%22%3A%22external_link%22%2C%22custom_src%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fimage-04.png%22%2C%22img_size%22%3A%22thumbnail%22%2C%22external_img_alt%22%3A%22External%20image%22%2C%22onclick%22%3A%22video%22%2C%22video_link%22%3A%22%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D7e90gBu4pas%22%2C%22icon_class%22%3A%22pink%22%2C%22img_link_target%22%3A%22_self%22%7D%2C%7B%22title%22%3A%22Elegant%20User%20Interface%22%2C%22subtitle%22%3A%22Luctus%20congue%20magna%20at%20pretium%20purus%20pretium%20ligula%20rutrum%20neque%20incidunt%20tempor%20laoreet%20ipsum%20rhoncus%2C%20tempor%20posuere%20ligula%20varius%20donec%20purus%20feugiat%22%2C%22source%22%3A%22external_link%22%2C%22custom_src%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fuploads%2F2019%2F04%2Fimage-02.png%22%2C%22img_size%22%3A%22thumbnail%22%2C%22external_img_alt%22%3A%22External%20image%22%2C%22video_link%22%3A%22https%3A%2F%2Fwww.youtube.com%2Fembed%2FSZEflIVnhH8%22%2C%22icon_class%22%3A%22tra%22%2C%22img_link_target%22%3A%22_self%22%7D%5D"][/vc_column][/vc_row][/vc_section]';



	$templates['Section: Content 04'] = '[vc_section section_type="content" content_type="4" parallax_image_attachment="inherit" el_class="content-section division"][vc_row][vc_column width="1/2"][perch_image custom_src="'.get_template_directory_uri().'/images/image-04.png" el_class="img-block"][/vc_column][vc_column width="1/2" el_class="txt-block"][perch_cbox display_as="cbox-3" icon_type="flaticon" icon_flaticon="flaticon-156-add" icon_size="icon" icon_color="black-color" title="Extended Features" subtitle="Velna iaculis odio auctor integer congue impedit magna at dolor vitae gravida donec mauris lectus luctus ultrice tellus viverra potenti neque"][perch_cbox display_as="cbox-3" icon_type="flaticon" icon_flaticon="flaticon-073-layer-1" icon_size="icon" icon_color="black-color" title="Transparent Workflow" subtitle="Velna iaculis odio auctor integer congue impedit magna at dolor vitae gravida donec mauris lectus luctus ultrice tellus viverra potenti neque"][perch_cbox display_as="cbox-3" icon_type="flaticon" icon_flaticon="flaticon-129-search" icon_size="icon" icon_color="black-color" title="SEO & SMM Services" subtitle="Velna iaculis odio auctor integer congue impedit magna at dolor vitae gravida donec mauris lectus luctus ultrice tellus viverra potenti neque"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 05'] = '[vc_section section_type="content" content_type="5" parallax_image_attachment="inherit" padding_top="pt-100" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="1/2"][perch_content_text name="" title="Choose a powerful design for your website" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle="An nullam tempor sapien, eget gravida donec enim ipsum porta justo integer at odio velna auctor integer congue. Justo odio integer a velna lectus aenean magna and mauris lectus laoreet tempor" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" enable_content_list="yes" content_list="Vitae auctor integer congue magna at pretium purus pretium ligula rutrumluctus risus ac risus auctor,Tempor sapien gravida donec enim ipsum blandit magna at purus pretium ligula rutrum luctus gravida donec porta justo integer,Justo odio integer a velna lectus aenean magna and mauris lectus pretium ligula rutrum luctus risus ac risus auctor gravida donec" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="content-txt content-left"]
		<h5 class="h5-sm wow fadeInUp" data-wow-delay="0.7s">DataBase Backup</h5>
		[/perch_content_text][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][perch_content_image display_as="content-5-img" custom_src="'.get_template_directory_uri().'/images/image-10.png" max_width="yes"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 06'] = '[vc_section section_type="content" content_type="6" bg_class="bg-tra" parallax_image_attachment="inherit" padding_top="pt-100" padding_class="" el_class="content-section division"][vc_row][vc_column width="1/2"][perch_image custom_src="'.get_template_directory_uri().'/images/image-12.png" max_width="yes" el_class="content-6-img"][/vc_column][vc_column width="1/2" el_class="txt-block "][perch_content_text name="" title="Organized Code" title_font_container="tag:h5|size:md|text_color:Default|text_underline:none|" subtitle="An enim nullam tempor ac tincidunt ligula massa in faucibus orci luctus et ultrices sapien gravida donec pretium ipsum porta justo integer at odio velna vitae auctor integer congue magna" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" enable_content="" el_class="steelblue-color" pleft="pl-30" pright="pr-30"][/perch_content_text][perch_content_text name="" title="Free Updates" title_font_container="tag:h5|size:md|text_color:Default|text_underline:none|" subtitle="An enim nullam tempor sapien gravida donec pretium ipsum porta justo integer at odio velna vitae auctor integer congue magna purus pretium ligula rutrum luctus ultrice aliquam a augue suscipit" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" enable_content="" el_class="steelblue-color" pleft="pl-30" pright="pr-30"][/perch_content_text][perch_content_text name="" title="Premium Support" title_font_container="tag:h5|size:md|text_color:Default|text_underline:none|" subtitle="An enim nullam tempor sapien gravida donec pretium ipsum porta justo integer at odio velna vitae integer congue magna purus" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" enable_content="" el_class="steelblue-color" pleft="pl-30" pright="pr-30"][/perch_content_text][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 07'] = '[vc_section section_type="content" content_type="7" parallax_image_attachment="inherit" el_class="content-section division"][vc_row][vc_column width="1/2"][perch_content_text align="" name="Totally Optimized" name_font_container="tag:span|text_color:default-color|text_underline:none|extra_class:section-id primary-color|" '.esc_html($empty_title).' '.esc_html($empty_subtitle).' enable_textfield="yes" textfield_area="We provide wide range of business services" textfield_area_font_container="tag:h3|size:md|text_color:Default|" enable_content_list="yes" list_type="cbox" content_list="Velna iaculis odio auctor integer congue impedit magna viverra at dolor vitae donec mauris lectus laoreet gestas neque undo luctus feugiat. Justo integer at odio velna vitae auctor integer congue ,An enim nullam tempor sapien gravida donec pretium and ipsum porta justo integer at velna vitae auctor integer congue a magna ipsum purus pretium ligula rutrum luctus ultrice. Aliquam a augue suscipit luctus neque purus ipsum neque dolor feugiat" enable_technologies="yes" techs_group="%5B%7B%22title%22%3A%22HTML5%22%2C%22icon%22%3A%22fa%20fa-html5%22%7D%2C%7B%22title%22%3A%22CSS3%22%2C%22icon%22%3A%22fa%20fa-css3%22%7D%2C%7B%22title%22%3A%22jsfiddle%22%2C%22icon%22%3A%22fa%20fa-jsfiddle%22%7D%2C%7B%22title%22%3A%22git%22%2C%22icon%22%3A%22fa%20fa-git%22%7D%2C%7B%22title%22%3A%22WordPress%22%2C%22icon%22%3A%22fa%20fa-wordpress%22%7D%2C%7B%22title%22%3A%22mixcloud%22%2C%22icon%22%3A%22fa%20fa-mixcloud%22%7D%5D"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][perch_image custom_src="'.get_template_directory_uri().'/images/image-08.png" max_width="yes" el_class="content-7-img"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 08'] = '[vc_section section_type="content" content_type="8" bg_class="bg-tra" parallax_image_attachment="inherit" el_class="content-section division"][vc_row][vc_column width="1/2"][perch_image custom_src="'.get_template_directory_uri().'/images/image-12.png" max_width="yes" el_class="content-8-img"][/vc_column][vc_column width="1/2"][perch_cbox icon_type="fontawesome" icon_fontawesome="fa fa-calendar-check-o" icon_size="sm" pleft="pl-30" pright="pr-30"][perch_cbox icon_type="fontawesome" icon_fontawesome="fa fa-globe" icon_size="sm" title="Multi-language Support" subtitle="Aliquam a augue suscipit, luctus neque purus ipsum odio velna vitae auctor integer congue magna at pretium purus pretium undo blandit posuere ligula varius magna congue ipsum gravida purus" pleft="pl-30" pright="pr-30" el_class="mt-30"][perch_cbox icon_type="fontawesome" icon_fontawesome="fa fa-pencil-square-o" icon_size="sm" title="Real Time Customization" subtitle="An enim nullam tempor sapien gravida donec blandit ipsum porta justo integer odio velna vitae auctor integer congue magna ipsum pretium purus ante pretium ligula ultrice ligula auctor risus" pleft="pl-30" pright="pr-30" el_class="mt-30"][perch_cbox icon_type="fontawesome" icon_fontawesome="fa fa-question-circle-o" icon_size="sm" title="Rapid Customer Support" subtitle="Gravida donec blandit ipsum porta justo integer odio velna vitae auctor integer congue magna at pretium purus ligula rutrum an integer congue magna at purus neque dolor enim gravida" pleft="pl-30" pright="pr-30" el_class="mt-30"][/vc_column][/vc_row][/vc_section]';


	$templates['Section: Content 10'] = '[vc_section section_type="content" content_type="10" parallax_image_attachment="inherit" el_class="content-section division"][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_content_text align="text-center" name="" title="Something Different, Something New" title_font_container="tag:h3|size:md|text_color:Default|text_underline:none|" subtitle="Semper lacus cursus porta, feugiat primis in ultrice ligula tempus auctor ipsum and mauris lectus enim ipsumю At sagittis congue augue egestas egestas donec mauris ultrice" subtitle_font_container="tag:p|size:lg|text_color:grey-color|text_underline:none|" enable_content="" el_class="txt-block"][/perch_content_text][vc_row_inner][vc_column_inner][perch_image align="text-center" custom_src="'.get_template_directory_uri().'/images/image-10.png" mtop="mt-0" el_class="content-10-img"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][/vc_section]';


	
	foreach ($templates as $key => $template) {
		$data               = array(); 
	    $data['name']       = esc_attr($key); // Assign name for your custom template
	    $data['weight']     = 0; 
	    $data['image_path'] = '';
	    $data['custom_class'] = ''; // CSS class name
	    $data['content']    = $template;

	    vc_add_default_templates( $data );
	}
      

}



