<?php
add_action( 'vc_load_default_templates_action','shiftkey_hero_sections_for_vc' ); // Hook in
function shiftkey_hero_sections_for_vc() {
	$templates = array();

	$empty_value = '';

	$templates['Section: Hero 01'] = '[vc_section section_type="hero" hero_type="1" parallax_image_attachment="scroll" padding_class=""][vc_row][vc_column width="1/2"][perch_hero_text title_font_container="tag:h2|text_color:Default|text_underline:none|" subtitle="" enable_content_list="yes" content_list="Ligula risus auctor and egestas mauris donec iaculis,Sagittis congue augue egestas ligula egestas magna,Feugiat primis ligula risus auctor augue an egestas mauris viverra tortor in iaculis magna feugiat gravida" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Buy%20Now%20For%20-%20%2415%22%2C%22button_url%22%3A%22%23%22%2C%22button_style%22%3A%22btn-yellow%22%2C%22button_hover_style%22%3A%22default%22%2C%22button_target%22%3A%22_blank%22%7D%2C%7B%22button_type%22%3A%22video_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fgoogleplay.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Take%20Quick%20Tour%20%22%2C%22button_url%22%3A%22%23%22%2C%22button_style%22%3A%22btn-tra%22%2C%22button_hover_style%22%3A%22default%22%2C%22button_target%22%3A%22_blank%22%7D%5D" buttons_desc="" el_class="hero-txt white-color hero-btns mt-35"][/vc_column][vc_column width="1/2"][perch_hero_image align="text-left" el_class="hero-1-img img text-center"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 02'] = '[vc_section section_type="hero" hero_type="2" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-2-txt"][vc_row parallax_image_attachment="inherit" el_id="hero-2-content"][vc_column width="2/12"][/vc_column][vc_column width="8/12"][perch_hero_text align="text-center" title="The best landing page to bring new customers to your business" title_font_container="tag:h3|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor augue egestas and mauris viverra tortor in iaculis magna undo ipsum mauris in placerat feugiat ligula risus auctor"][perch_newsletter_form inline_form="yes" button_text="Get Started" button_style="btn-green" subtitle="Try ShiftKey free for 14 days. No risk, and no credit card required." el_class="hero-newsletter-form"][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][vc_row parallax_image_attachment="inherit" el_class="hero-2-img division"][vc_column][vc_row_inner][vc_column_inner width="2/12"][/vc_column_inner][vc_column_inner width="8/12"][perch_image custom_src="'.get_template_directory_uri().'/images/hero-2-img.png" onclick="video" icon_class="coral"][/vc_column_inner][vc_column_inner width="2/12"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 03'] = '[vc_section section_type="hero" hero_type="3" bg_class="bg-tra" parallax_image_attachment="scroll" padding_class="" el_class="hero-section division"][vc_row parallax_image_attachment="inherit"][vc_column width="5/12"][perch_hero_text title="Best editor for your media files" title_font_container="tag:h2|text_color:Default|text_underline:none|font_size:3.4rem|" subtitle="Feugiat primis ligula risus auctor egestas augue mauri viverra tortor in iaculis placerat magna feugiat mauris ipsum in viverra tortor gravida purus pretium" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22img_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Appstore%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-white%20tra-hover%22%7D%2C%7B%22button_type%22%3A%22img_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fgoogleplay.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Googleplay%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-white%20tra-hover%22%7D%5D" buttons_desc="" el_class="white-color txt-500" mbottom="mb-40"][/vc_column][vc_column width="7/12"][perch_hero_image display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-3-img.png" el_class="hero-3-img"][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Hero 04'] = '[vc_section section_type="hero" hero_type="4" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section division"][vc_row][vc_column width="6/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-4-img-1.png" el_class="hero-4-img"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][perch_hero_text title="Every great business starts with an idea" title_font_container="tag:h2|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor augue egestas mauri viverra tortor in iaculis magna feugiat mauris ipsum in placerat viverra tortor gravida purus pretium" subtitle_font_container="tag:p|size:md|text_color:grey-color|text_underline:none|" el_class="hero-txt steelblue-color"][perch_newsletter_form inline_form="yes" button_text="Get Started" button_style="btn-lightgreen" subtitle="Try ShiftKey free for 14 days. No risk, and no credit card required." el_class="hero-newsletter-form"][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Hero 05'] = '[vc_section enable_inner="yes" section_type="hero" hero_type="5" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section" inner_el_class="hero-overlay division"][vc_row parallax_image_attachment="inherit"][vc_column][perch_video_bg][/vc_column][/vc_row][vc_row][vc_column width="1/2"][perch_hero_text name="Everyone wants to be unique" name_font_container="tag:h5|size:xs|text_color:Default|text_underline:none|" title="Create your unique website with ShiftKey in just few hours" title_font_container="tag:h2|text_color:Default|text_underline:none|" subtitle="" enable_content_list="yes" list_type="content-list" content_list="Ligula risus auctor augue egestas mauris viverra iaculis,Sagittis congue augue egestas volutpat egestas magna,Feugiat primis ligula risus auctor augue an egestas mauris viverra tortor in iaculis magna feugiat laborum donec" el_class="hero-txt white-color"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][contact-form-7 id="759"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 06'] = '[vc_section enable_inner="yes" section_type="hero" hero_type="6" bg_class="bg-tra" parallax_image_attachment="scroll" padding_class="" el_class="hero-section division" inner_el_class="hero-overlay division"][vc_row][vc_column width="2/12"][/vc_column][vc_column width="8/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-logo.png" el_class="hero-logo"][perch_hero_text align="text-center" title="Ultimate Responsive Bootstrap 4 Software & Startup Premium Landing Page Template" title_font_container="tag:h5|text_color:Default|text_underline:none|" subtitle="" el_class="hero-txt white-color" mbottom="mb-50"][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][vc_row][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_image align="text-center" custom_src="http://localhost/projects/shiftkey/wp-content/uploads/2019/04/hero-6-img.png" onclick="video" icon_class="coral"][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 07'] = '[vc_section section_type="hero" hero_type="7" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section division"][vc_row][vc_column width="1/2"][perch_hero_text title="Launch your new website and start to engage new users" title_font_container="tag:h2|text_color:Default|text_underline:none|font_weight:500|" subtitle="Feugiat primis ligula risus auctor laoreet augue egestas mauris viverra tortor in iaculis pretium magna at mauris rhoncus ipsum placerat feugiat primis in ultrice" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Start%20Free%20Trial%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-yellow%22%7D%2C%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fgoogleplay.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Take%20Quick%20Tour%20%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-yellow%22%7D%5D" buttons_desc="" el_class="hero-txt white-color" mbottom="mb-40" pleft="pl-15" pright="pr-15"][/vc_column][vc_column width="1/2"][perch_hero_image display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-7-img.png" max_width="yes" el_class="hero-7-img" pleft="pl-15" pright="pr-15"][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Hero 08'] = '[vc_section section_type="hero" hero_type="8" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section division"][vc_row][vc_column width="2/12"][/vc_column][vc_column width="8/12"][perch_hero_text align="text-center" title="We deliver your emotions" title_font_container="tag:h2|text_color:lightgreen-color|text_underline:none|" subtitle="Feugiat primis ligula risus auctor augue egestas mauri viverra tortor in iaculis magna feugiat mauris ipsum in placerat viverra gravida" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Download%20Free%20Today%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-lightgrey%22%7D%5D" buttons_desc=""][vc_row_inner][vc_column_inner][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-8-img.png" el_class="hero-8-img"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 09'] = '[vc_section section_type="hero" hero_type="9" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section division"][vc_row][vc_column width="5/12"][perch_hero_text title="Stay connected with your friends" title_font_container="tag:h2|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor egestas augue viverra mauri tortor in iaculis magna feugiat mauris ipsum and placerat viverra tortor gravida purus pretium" el_class="hero-txt white-color" mbottom="mb-40"][perch_newsletter_form inline_form="yes" button_text="Get Started" button_style="btn-green" subtitle="Try ShiftKey free for 14 days. No risk, and no credit card required." el_class="hero-newsletter-form white-color"][/vc_column][vc_column width="7/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-9-img.png" max_width="yes" el_class="hero-9-img"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 10'] = '[vc_section section_type="hero" hero_type="10" bg_class="bg-tra" parallax_image_attachment="inherit" padding_class="" el_class="hero-section division"][vc_row][vc_column width="2/12"][/vc_column][vc_column width="8/12"][perch_hero_text align="text-center" title="Create awesome mobile-friendly websites with ShiftKey" title_font_container="tag:h3|text_color:Default|text_underline:none|" subtitle="" el_class="hero-txt steelblue-color" mbottom="mb-60"][perch_newsletter_form inline_form="yes" button_text="Get Started" button_style="btn-lightgreen" subtitle="Try ShiftKey free for 14 days. No risk, and no credit card required." el_class="hero-newsletter-form"][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][vc_row][vc_column][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-10-img.png" el_class="hero-10-img"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 11'] = '[vc_section section_type="hero" hero_type="11" bg_class="bg-tra" parallax_image_attachment="scroll" padding_class="" el_class="hero-section division"][vc_row][vc_column width="5/12"][perch_hero_text title="Showcase your App in easy way" title_font_container="tag:h2|text_color:Default|text_underline:none|" subtitle="" enable_content_list="yes" list_type="content-list" content_list="Ligula risus auctor augue egestas at mauris iaculis,Feugiat primis ligula risus auctor augue an egestas mauris viverra tortor in iaculis magna feugiat" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22img_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fuploads%2F2019%2F04%2Fappstore-tra-white.png%22%2C%22img_btn_size%22%3A%22140%22%2C%22button_text%22%3A%22Appstore%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-white%20tra-hover%22%7D%2C%7B%22button_type%22%3A%22img_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fuploads%2F2019%2F04%2Fgoogleplay-tra-white.png%22%2C%22img_btn_size%22%3A%22140%22%2C%22button_text%22%3A%22Googleplay%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-white%20tra-hover%22%7D%5D" buttons_desc="" el_class="hero-txt white-color"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="1/2"][perch_hero_image display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-11-img.png" el_class="hero-11-img"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 12'] = '[vc_section section_type="hero" hero_type="12" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section division"][vc_row][vc_column width="5/12"][perch_hero_text title="Make Your Website More Powerful" title_font_container="tag:h2|text_color:Default|text_underline:none|" subtitle="Donec vel sapien augue integer urna turpis vel cursus porta, mauris sed augue luctus magna dolor luctus neque primis libero tempor" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Buy%20Now%20For%20-%20%2415%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-lightblue%22%7D%5D" buttons_desc="" mbottom="mb-40"][/vc_column][vc_column width="7/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-12-img.png" el_class="hero-12-img" mbottom="mb-40"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 13'] = '[vc_section section_type="hero" hero_type="13" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section division"][vc_row][vc_column width="1/12"][/vc_column][vc_column width="10/12"][vc_row_inner][vc_column_inner width="5/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-13-img.png" el_class="hero-13-img" mbottom="mb-40"][/vc_column_inner][vc_column_inner width="1/12"][/vc_column_inner][vc_column_inner width="6/12"][perch_hero_text title="Smart & Secure Mobile Banking" title_font_container="tag:h2|size:huge|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor augue egestas mauri viverra tortor in iaculis magna feugiat mauris ipsum in placerat viverra tortor gravida purus pretium" subtitle_font_container="tag:p|size:md|text_color:grey-color|text_underline:none|" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22img_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Appstore%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-white%20tra-hover%22%7D%2C%7B%22button_type%22%3A%22img_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fgoogleplay.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Googleplay%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-white%20tra-hover%22%7D%5D" buttons_desc="" mbottom="mb-40"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 14'] = '[vc_section section_type="hero" hero_type="14" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class="" el_class="hero-section division"][vc_row][vc_column width="2/12"][/vc_column][vc_column width="8/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-logo-color.png" el_class="hero-logo" mbottom="mb-35"][perch_hero_text align="text-center" title="Need modern & powerful website? We are here to help you" title_font_container="tag:h3|text_color:Default|text_underline:none|font_weight:700|" subtitle="Feugiat primis ligula risus auctor augue egestas and mauris viverra tortor in iaculis magna undo ipsum mauris placerat feugiat ligula risus auctor risus auctor" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Download%20Free%20Today%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-lightgreen%22%7D%5D" buttons_desc=""][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 15'] = '[vc_section section_type="hero" hero_type="15" bg_class="bg-tra" parallax_image_attachment="scroll" padding_class="" el_class="hero-section division"][vc_row][vc_column width="5/12"][perch_hero_text title="We build websites for your business" title_font_container="tag:h2|text_color:Default|text_underline:none|font_weight:500|" subtitle="" enable_content_list="yes" list_type="content-list" content_list="Ligula risus auctor augue egestas at mauris,Sagittis congue augue egestas egestas magna,Feugiat primis ligula risus auctor augue an egestas mauris viverra tortor in iaculis magna feugiat" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Buy%20Now%20For%20-%20%2415%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-yellow%22%7D%2C%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Fprojects%2Fshiftkey%2Fwp-content%2Fthemes%2Fshiftkey%2Fimages%2Fgoogleplay.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Take%20Quick%20Tour%20%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-yellow%22%7D%5D" buttons_desc="" el_class="hero-txt white-color"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="6/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-15-img.png" max_width="yes" el_class="hero-15-img"][/vc_column][/vc_row][/vc_section]';

	
	foreach ($templates as $key => $template) {
		$data               = array(); 
	    $data['name']       = esc_attr($key); // Assign name for your custom template
	    $data['weight']     = 0; 
	    $data['image_path'] = '';
	    $data['custom_class'] = ''; // CSS class name
	    $data['content']    = $template;

	    vc_add_default_templates( $data );
	}
      

}



